package sk.upjs.ics.diagnostika5.ActivityAFragmenty;

import android.app.AlertDialog;
import android.content.AsyncQueryHandler;
import android.content.ContentValues;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.TimePicker;
import android.widget.Toast;

import com.facebook.stetho.Stetho;

import java.util.Calendar;

import butterknife.BindView;
import butterknife.ButterKnife;
import sk.upjs.ics.diagnostika5.R;
import sk.upjs.ics.diagnostika5.databaza.Provider;

public class PridajManualneActivity extends AppCompatActivity {

    @BindView(R.id.menoPridajMEditText)
    EditText menoPridajMEditText;

    @BindView(R.id.datumDatePicker)
    DatePicker datumDatePicker;
    @BindView(R.id.casTimePicker)
    TimePicker casTimePicker;

    @BindView(R.id.hl1EditText)
    EditText hl1EditText;
    @BindView(R.id.hl2EditText)
    EditText hl2EditText;
    @BindView(R.id.hl3EditText)
    EditText hl3EditText;
    @BindView(R.id.hl4EditText)
    EditText hl4EditText;
    @BindView(R.id.hl5EditText)
    EditText hl5EditText;
    @BindView(R.id.hl6EditText)
    EditText hl6EditText;

    @BindView(R.id.hr1EditText)
    EditText hr1EditText;
    @BindView(R.id.hr2EditText)
    EditText hr2EditText;
    @BindView(R.id.hr3EditText)
    EditText hr3EditText;
    @BindView(R.id.hr4EditText)
    EditText hr4EditText;
    @BindView(R.id.hr5EditText)
    EditText hr5EditText;
    @BindView(R.id.hr6EditText)
    EditText hr6EditText;

    @BindView(R.id.fl1EditText)
    EditText fl1EditText;
    @BindView(R.id.fl2EditText)
    EditText fl2EditText;
    @BindView(R.id.fl3EditText)
    EditText fl3EditText;
    @BindView(R.id.fl4EditText)
    EditText fl4EditText;
    @BindView(R.id.fl5EditText)
    EditText fl5EditText;
    @BindView(R.id.fl6EditText)
    EditText fl6EditText;

    @BindView(R.id.fr1EditText)
    EditText fr1EditText;
    @BindView(R.id.fr2EditText)
    EditText fr2EditText;
    @BindView(R.id.fr3EditText)
    EditText fr3EditText;
    @BindView(R.id.fr4EditText)
    EditText fr4EditText;
    @BindView(R.id.fr5EditText)
    EditText fr5EditText;
    @BindView(R.id.fr6EditText)
    EditText fr6EditText;

    @BindView(R.id.poznamkaPridajMEditText)
    EditText poznamkaPridajMEditText;

    public static final String AUTOGENERATED_ID = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pridaj_manualne);

        ButterKnife.bind(this);
        Stetho.initializeWithDefaults(this);

        casTimePicker.setIs24HourView(true);

    }

    public void ulozitZaznam(View view) {

        String meno = menoPridajMEditText.getText().toString();

        if(meno.isEmpty()){
            new AlertDialog.Builder(this)
                    .setMessage("Nevyplnili ste meno!")
                    .setTitle("Upozornenie")
                    .setNeutralButton("Close", null)
                    .show();
        }else {
            try {
                int hl1 = Integer.parseInt(hl1EditText.getText().toString());
                int hl2 = Integer.parseInt(hl2EditText.getText().toString());
                int hl3 = Integer.parseInt(hl3EditText.getText().toString());
                int hl4 = Integer.parseInt(hl4EditText.getText().toString());
                int hl5 = Integer.parseInt(hl5EditText.getText().toString());
                int hl6 = Integer.parseInt(hl6EditText.getText().toString());

                int hr1 = Integer.parseInt(hr1EditText.getText().toString());
                int hr2 = Integer.parseInt(hr2EditText.getText().toString());
                int hr3 = Integer.parseInt(hr3EditText.getText().toString());
                int hr4 = Integer.parseInt(hr4EditText.getText().toString());
                int hr5 = Integer.parseInt(hr5EditText.getText().toString());
                int hr6 = Integer.parseInt(hr6EditText.getText().toString());

                int fl1 = Integer.parseInt(fl1EditText.getText().toString());
                int fl2 = Integer.parseInt(fl2EditText.getText().toString());
                int fl3 = Integer.parseInt(fl3EditText.getText().toString());
                int fl4 = Integer.parseInt(fl4EditText.getText().toString());
                int fl5 = Integer.parseInt(fl5EditText.getText().toString());
                int fl6 = Integer.parseInt(fl6EditText.getText().toString());

                int fr1 = Integer.parseInt(fr1EditText.getText().toString());
                int fr2 = Integer.parseInt(fr2EditText.getText().toString());
                int fr3 = Integer.parseInt(fr3EditText.getText().toString());
                int fr4 = Integer.parseInt(fr4EditText.getText().toString());
                int fr5 = Integer.parseInt(fr5EditText.getText().toString());
                int fr6 = Integer.parseInt(fr6EditText.getText().toString());

                int rok = datumDatePicker.getYear();
                int mesiac = datumDatePicker.getMonth();
                int den = datumDatePicker.getDayOfMonth();
                int hodina = casTimePicker.getCurrentHour();
                int minuty = casTimePicker.getCurrentMinute();
                Calendar calendar = Calendar.getInstance();
                calendar.set(rok, mesiac, den, hodina, minuty);

                String poznmka = poznamkaPridajMEditText.getText().toString();

                Uri uri = Provider.CONTENT_URI;
                ContentValues values = new ContentValues();
                values.put(Provider.Zaznam._ID, AUTOGENERATED_ID);
                values.put(Provider.Zaznam.MENO, meno);
                values.put(Provider.Zaznam.DATUM_A_CAS, calendar.getTimeInMillis() / 1000L);
                values.put(Provider.Zaznam.POZNAMKA, poznmka);


                values.put(Provider.Zaznam.HL1, hl1);
                values.put(Provider.Zaznam.HL2, hl2);
                values.put(Provider.Zaznam.HL3, hl3);
                values.put(Provider.Zaznam.HL4, hl4);
                values.put(Provider.Zaznam.HL5, hl5);
                values.put(Provider.Zaznam.HL6, hl6);

                values.put(Provider.Zaznam.HR1, hr1);
                values.put(Provider.Zaznam.HR2, hr2);
                values.put(Provider.Zaznam.HR3, hr3);
                values.put(Provider.Zaznam.HR4, hr4);
                values.put(Provider.Zaznam.HR5, hr5);
                values.put(Provider.Zaznam.HR6, hr6);

                values.put(Provider.Zaznam.FL1, fl1);
                values.put(Provider.Zaznam.FL2, fl2);
                values.put(Provider.Zaznam.FL3, fl3);
                values.put(Provider.Zaznam.FL4, fl4);
                values.put(Provider.Zaznam.FL5, fl5);
                values.put(Provider.Zaznam.FL6, fl6);

                values.put(Provider.Zaznam.FR1, fr1);
                values.put(Provider.Zaznam.FR2, fr2);
                values.put(Provider.Zaznam.FR3, fr3);
                values.put(Provider.Zaznam.FR4, fr4);
                values.put(Provider.Zaznam.FR5, fr5);
                values.put(Provider.Zaznam.FR6, fr6);

                AsyncQueryHandler insertHandler = new AsyncQueryHandler(getContentResolver()) {
                    @Override
                    protected void onDeleteComplete(int token, Object cookie, int result) {
                        Toast.makeText(PridajManualneActivity.this, "Záznam bol uložený", Toast.LENGTH_SHORT)
                                .show();
                    }
                };

                insertHandler.startInsert(0, null, uri, values);

                Intent intent = new Intent(getApplicationContext(), ZaznamListActivity.class);
                startActivity(intent);

            } catch (NumberFormatException e) {
                new AlertDialog.Builder(this)
                        .setMessage("Nevyplnili ste všetky namerané hodnoty!")
                        .setTitle("Upozornenie")
                        .setNeutralButton("Close", null)
                        .show();
            }
        }
    }
}
