package sk.upjs.ics.diagnostika5.ActivityAFragmenty;

import android.app.AlertDialog;
import android.app.LoaderManager;
import android.content.CursorLoader;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.Loader;
import android.database.Cursor;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.SimpleCursorAdapter;

import com.facebook.stetho.Stetho;

import java.util.Date;

import butterknife.BindView;
import butterknife.ButterKnife;
import sk.upjs.ics.diagnostika5.R;
import sk.upjs.ics.diagnostika5.Zaznam;
import sk.upjs.ics.diagnostika5.ZaznamCursorAdapter;
import sk.upjs.ics.diagnostika5.databaza.Provider;

public class ZaznamListActivity extends AppCompatActivity implements LoaderManager.LoaderCallbacks<Cursor>{

    @BindView(R.id.zaznamyListView)
    ListView zaznamyListView;

    private SimpleCursorAdapter adapter;

    public static final String AUTOGENERATED_ID = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_zaznam_list);

        ButterKnife.bind(this);
        Stetho.initializeWithDefaults(this);

        getLoaderManager().initLoader(0, Bundle.EMPTY, this);

        String[] from = {Provider.Zaznam.MENO};
        int[] to = {android.R.id.text1};

        adapter = new ZaznamCursorAdapter(this, R.layout.zaznam_item,null,from,to);
        zaznamyListView.setAdapter(adapter);

        zaznamyListView.setOnItemClickListener(new AdapterView.OnItemClickListener(){

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Cursor c = (Cursor) zaznamyListView.getAdapter().getItem(position);

                Zaznam z = new Zaznam();
                z.set_id(c.getInt(c.getColumnIndex(Provider.Zaznam._ID)));
                z.setMeno(c.getString(c.getColumnIndex(Provider.Zaznam.MENO)));
                long datumDelene1000 = c.getInt(c.getColumnIndex(Provider.Zaznam.DATUM_A_CAS));
                z.setDatumACas(new Date(datumDelene1000*1000L));
                z.setPoznamka(c.getString(c.getColumnIndex(Provider.Zaznam.POZNAMKA)));

                z.setHodnotu(1,c.getInt(c.getColumnIndex(Provider.Zaznam.HL1)));
                z.setHodnotu(2,c.getInt(c.getColumnIndex(Provider.Zaznam.HL2)));
                z.setHodnotu(3,c.getInt(c.getColumnIndex(Provider.Zaznam.HL3)));
                z.setHodnotu(4,c.getInt(c.getColumnIndex(Provider.Zaznam.HL4)));
                z.setHodnotu(5,c.getInt(c.getColumnIndex(Provider.Zaznam.HL5)));
                z.setHodnotu(6,c.getInt(c.getColumnIndex(Provider.Zaznam.HL6)));

                z.setHodnotu(7,c.getInt(c.getColumnIndex(Provider.Zaznam.HR1)));
                z.setHodnotu(8,c.getInt(c.getColumnIndex(Provider.Zaznam.HR2)));
                z.setHodnotu(9,c.getInt(c.getColumnIndex(Provider.Zaznam.HR3)));
                z.setHodnotu(10,c.getInt(c.getColumnIndex(Provider.Zaznam.HR4)));
                z.setHodnotu(11,c.getInt(c.getColumnIndex(Provider.Zaznam.HR5)));
                z.setHodnotu(12,c.getInt(c.getColumnIndex(Provider.Zaznam.HR6)));

                z.setHodnotu(13,c.getInt(c.getColumnIndex(Provider.Zaznam.FL1)));
                z.setHodnotu(14,c.getInt(c.getColumnIndex(Provider.Zaznam.FL2)));
                z.setHodnotu(15,c.getInt(c.getColumnIndex(Provider.Zaznam.FL3)));
                z.setHodnotu(16,c.getInt(c.getColumnIndex(Provider.Zaznam.FL4)));
                z.setHodnotu(17,c.getInt(c.getColumnIndex(Provider.Zaznam.FL5)));
                z.setHodnotu(18,c.getInt(c.getColumnIndex(Provider.Zaznam.FL6)));

                z.setHodnotu(19,c.getInt(c.getColumnIndex(Provider.Zaznam.FR1)));
                z.setHodnotu(20,c.getInt(c.getColumnIndex(Provider.Zaznam.FR2)));
                z.setHodnotu(21,c.getInt(c.getColumnIndex(Provider.Zaznam.FR3)));
                z.setHodnotu(22,c.getInt(c.getColumnIndex(Provider.Zaznam.FR4)));
                z.setHodnotu(23,c.getInt(c.getColumnIndex(Provider.Zaznam.FR5)));
                z.setHodnotu(24,c.getInt(c.getColumnIndex(Provider.Zaznam.FR6)));

                //Intent intent = new Intent(getApplicationContext(),ZaznamDetailActivity.class);
                Intent intent = new Intent(getApplicationContext(),ZaznamDetailFrActivity.class);
                Bundle bundle = new Bundle();
                bundle.putSerializable("zaznam", z);
                intent.putExtras(bundle);
                startActivity(intent);
            }
        });

    }

    @Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        CursorLoader loader = new CursorLoader(this);
        loader.setUri(Provider.CONTENT_URI);
        return loader;
    }

    @Override
    public void onLoadFinished(Loader<Cursor> loader, Cursor data) {
            this.adapter.swapCursor(data);
    }

    @Override
    public void onLoaderReset(Loader<Cursor> loader) {
        this.adapter.swapCursor(null);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_zaznam_list, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        if (id == R.id.pridajZaznamZoznamMenu){

            new AlertDialog.Builder(this)
                    .setMessage("Ako si prajete pridať záznam?")
                    .setTitle("Pridanie záznamu")
                    .setNeutralButton("Stopkami", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            Intent intent = new Intent(getApplicationContext(), PridajStopkamiActivity.class);
                            startActivity(intent);
                        }
                    })
                    .setNegativeButton("Manuálne", new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            Intent intent = new Intent(getApplicationContext(), PridajManualneActivity.class);
                            startActivity(intent);
                        }
                    })
                    .setPositiveButton("Close", null)
                    .show();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

}
